# encoding: UTF-8
# implement interface test script web-articles-recommend_list
TargetService: 
plan_name: 'Interfaces_web-articles-recommend_list'
owner: gang.wu@istuary.com
status: completed
created_dt: 2016-10-10
version: 1
last_modified_dt: 2016-10-10
timeout: 1200
actions: action_1

api_path: /api/website/articles/recommend_list
user:
  mobile: '15800000002'
  password: '123456'
unsign_test:
  - request: {}
    expected:
      code: 1
      message: ''
      length: 50
signin_test:
  - request: {}
    expected:
      code: 1
      message: ''
      length: 50        