ironhide_url: 'http://192.168.28.210/projects/59/test_plans'
ironhide:
- path: 'testing/interfaces'
  config_name: rspec_ironhide_interfaces
  marquee_name: IronHide
  tl_project_name: IronHide
  id_prefix: IH

