# encoding: UTF-8
TargetService: 
plan_name: ''
owner: gang.wu@istuary.com
status: Work In Progress
created_dt: 2016-08-22
version: 1
last_modified_dt: 2016-08-22
timeout: 1200
actions: action_1

api_path: /api/mobile/v1/articles/list
unsign_test:
  - request:
      sort: '0'
      page: '1'
    expected:
      code: 1
      message: ''
  - request:
      sort: '1'
      page: '1'
    expected:
      code: 1
      message: ''
  - request:
      sort: '2'
      page: '1'
    expected:
      code: 1
      message: ''
signin_test:
  - request:
      sort: '0'
      page: '1'
    expected:
      code: 1
      message: ''
  - request:
      sort: '1'
      page: '1'
    expected:
      code: 1
      message: ''
  - request:
      sort: '2'
      page: '1'
    expected:
      code: 1
      message: ''

            